import "./globals.css";

export const metadata = {
  title: "Climate Game",
  description: "Generated by Mehdi Paryabi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" className="scroll-smooth">
      <body>
        {children}
      </body>
    </html>
  );
}
